###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    webserver:
      build: phpdocker/nginx
      container_name: freechampionrotations-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      links: 
       - php-fpm

    php-fpm:
      build: phpdocker/php-fpm
      container_name: freechampionrotations-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - .env.example:/application/.env

    composer:
      build: phpdocker/composer
      container_name: freechampionrotations-composer
      working_dir: /application
      volumes: 
        - .:/application
      command: bash -c "echo downloading files, please wait.. && composer install --no-dev && composer dumpautoload && echo Composer dependendencies successfully installed, shutting down composer container..."
      depends_on: 
        - php-fpm