version: "3.8"
services:
        app:
                image: php:7.4-fpm
                container_name: app
                working_dir: /var/www/app
                restart: unless-stopped
                volumes:
                        - .:/var/www/app
                networks:
                        - fcrnetwork

        web:
                image: nginx:1.19.0-alpine
                container_name: web
                depends_on:
                        - app
                working_dir: /var/www/app
                restart: unless-stopped
                volumes:
                        - .:/var/www/app
                        - ./webserver/default.nginx:/etc/nginx/conf.d/default.conf
                ports:
                        - "80:80"
                networks:
                        - fcrnetwork

networks:
        fcrnetwork:
                driver: bridge
