version: "3.7"
services:
        app:
                build:
                        context: ./docker
                        dockerfile: Dockerfile
                container_name: app
                restart: unless-stopped
                volumes:
                        - .:/var/www/app
                networks:
                        - fcrnetwork

        web:
                image: nginx:1.19.0-alpine
                container_name: web
                restart: unless-stopped
                volumes:
                        - .:/var/www/app
                        - ./docker/default.nginx:/etc/nginx/conf.d/default.conf
                ports:
                        - "80:80"
                networks:
                        - fcrnetwork


        composer:
                image: composer:1.10.8
                container_name: composer
                command: composer install --no-dev
                working_dir: /var/www/app
                volumes:
                        - .:/var/www/app
                networks:
                        - fcrnetwork

networks:
        fcrnetwork:
                driver: bridge
