version: "3.1"
services:

    webserver:
      build: webserver
      container_name: freechampionrotations-webserver
      working_dir: /var/www/app
      volumes:
          - .:/var/www/app
      ports:
       - "8080:80"